spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/likelionspring

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create